name: paper-vector-db

networks:
    elastic:
        external: true
        name: elastic

volumes:
  es_data:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es-paper-vector-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

    stdin_open: true
    tty: true

    deploy:
      resources:
        limits:
          memory: 8GB


  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kib-paper-vector-search

    networks:
      - elastic
    ports:
      - "5601:5601"
